### ISSUE TITLE
comparison with pre-commit.com approach

### ISSUE THREAD

**Issue by ssbarnea** [csmart/openstack-git-hooks#1]
I do find the pre-commit hooks are something extremely useful and I hope that soon they will become mainstream.

I would like to hear why you ended up writing this hook when there are already well maintained solutions like http://pre-commit.com/ for example (there are few more I think, but this one looks the most mature at the moment).

**Comment by csmart** [comment]
Hi @ssbarnea I didn't even know about it, thanks :-)
